Django_Projects/to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include
import todolist.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(todolist.urls)),
]

Django_Projects/to_do_list/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [

    path('todolist/home', views.home, name='主页'),
    path('todolist/about', views.aboutPage, name='关于本站'),  # name=网址名字
    path('todolist/edit', views.edit, name='edit')
]

Django_Projects/to_do_list/todolist/models.py
from django.db import models

# Create your models here.

Django_Projects/to_do_list/todolist/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    context = {'content_post': request.POST, }
    # return render(request, "todolist/home.html", {'abc': str(request.POST)})
    # return render(request, "todolist/home.html", context.todo_add)
    return render(request, "todolist/home.html", context)


def aboutPage(request):
    return render(request, "todolist/about.html")


def edit(request):
    return render(request, "todolist/edit.html")

Django_Projects/to_do_list/todolist/templates/todolist/about.html
{% extends 'todolist/base.html' %}
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 标题 %}
  关于
{% endblock 标题 %}
  {% block 主体 %}
    <h4>这是一个todo list</h4>
  {% endblock 主体 %}

Django_Projects/to_do_list/todolist/templates/todolist/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{% block 标题 %}我的待办清单{% endblock 标题 %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
    <style type="text/css">
    	#topnav{
    		font-size: 1.35em;
    		padding-left: 5em;
    		height: 2em
    	}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link {% block 主页高亮 %}{% endblock 主页高亮 %}" href="{% url 'todolist:主页' %}">代办清单</a>
          </li>
          <li class="nav-item">
            <a class="nav-link  {% block 关于高亮 %}{% endblock 关于高亮 %}" href="{% url 'todolist:关于本站' %}">关于本站</a>
          </li>
        </ul>
        <!-- 点击提交，将todo_add这个input的值，以POST method提交到action地方去 -->
        <form class="form-inline mt-2 mt-md-0" method="POST" action="">
          {% csrf_token %}
          <input name="todo_add" class="form-control mr-sm-2" type="text" placeholder="代办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>
	<main>
	  {% block 主体 %}
	  	
	  {% endblock 主体 %}
  	</main>
	  <!-- Bootstrap core JavaScript
	  ================================================== -->
	  <!-- Placed at the end of the document so the pages load faster -->
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
	  </script>
  </body>
</html>

Django_Projects/to_do_list/todolist/templates/todolist/edit.html
{% extends 'todolist/base.html' %}
{% block 标题 %}编辑{% endblock 标题 %}
{% block 主体 %}
<form class="form-inline">
  <div class="form-groups mx-sm-3 mb-2">
    <label for="todolist" class="sr-only">散步</label>
    <input type="text" class="form-control" id="todolist" value='散步' placeholder="编辑">
    <small id="help" class="form-text text-muted">帮助</small>
  </div>
  <button type="submit" class="btn btn-primary mb-2">提交</button>
</form>
{% endblock 主体 %}

Django_Projects/to_do_list/todolist/templates/todolist/home.html
{% extends 'todolist/base.html' %}
{% block 主页高亮 %}active{% endblock 主页高亮 %}
{% block 主体 %}
<div class="table-responsive">
	<table class="table table-hover">
	  <thead class="thead-light">
	    <tr>
	      <th scope="col">序号</th>
	      <th scope="col">待办事项</th>
          <th scope="col">编辑</th>
	      <th scope="col">划掉</th>
	      <th scope="col">删除</th>
	    </tr>
	  </thead>
	  <tbody>
 	    <tr>
	      <th scope="row">1</th>
        <td>{{content_post.todo_add}}</td>
	      <td><a href="{% url 'todolist:edit' %}" class="text-success">编辑</a></td>
        <td><a href="#" class="text-info">划掉</a></td>
        <td><a href="#" class="text-danger">删除</a></td>
	    </tr>
	    <!--<tr>
	      <th scope="row">2</th>
	      <td>Jacob</td>
        <td><a href="{% url 'todolist:edit' %}" class="text-success">编辑</a></td>
        <td><a href="#" class="text-info">划掉</a></td>
        <td><a href="#" class="text-danger">删除</a></td>
	    </tr>
	    <tr> 
	      <th scope="row">3</th>
	      <td>Larry</td>
        <td><a href="{% url 'todolist:edit' %}" class="text-success">编辑</a></td>
        <td><a href="#" class="text-info">撤销</a></td>
	      <td><a href="#" class="text-danger">删除</a></td>
	    </tr> -->
	  </tbody>
	</table>
</div>
{% endblock 主体 %}